### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by xc0d3rz** [zaf/asterisk-speech-recog#25]
**\* THIS IS JUST A SUGGESTION NOT ISSUE **\* 
See this [Create your own Inline Translator like Skype Translator](https://gist.github.com/xc0d3rz/a1b493da55b17d143728bee7305ef823)

**Comment by zaf** [comment]
Thank you for that. Yes the idea is very good and it was one of the motives for releasing this set of tools. With the combination of  https://github.com/zaf/asterisk-speech-recog https://github.com/zaf/asterisk-googletts and https://github.com/zaf/asterisk-googletranslate someone could get something similar running on his Asterisk system or even on any other systems by using the CLI version of the tools. That was long ago of-course and since then new API have emerged.
