### ISSUE TITLE
Full duplex cmd Record

### ISSUE THREAD

**Issue by danishm1** [zaf/asterisk-speech-recog#27]
Hi,

In current situation caller has to record after the beep.

Is it possible caller can record during the prompt?

**Comment by poing** [comment]
The AGI command `RECORD FILE` does not start recording until the BEEP.  But you __could__ _omit_ the BEEP with short silence.

But the trouble is... the AGI command will not be called until __after__ you play a prompt.  Recording __during__ playback of the prompt is _tricky_!  Items in the dial-plan are processed sequentially.

However, I recently worked out a solution that should help.  Using the AGI `EXEC` command and the Asterisk `Monitor()`  and `StopMonitor()` commands to capture the audio during playback of the prompt.  

[read-and-record.agi](https://github.com/invitecomm/asterisk-ivr/tree/master/pigeonhole) is __probably__ what you're looking for.  

_Note: Current version is set to capture DTMF or perform ASR for_ __digits__ _and will require some modifications._

It also uses the Python Interface to Asterisk [PYST2](https://github.com/rdegges/pyst2).  Since the Google Cloud Speech API _beta_ has Python examples.
